# Generated by Django 4.1.7 on 2023-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_image_tvshow_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='creator',
            new_name='director',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='actors',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
