# Generated by Django 4.1.7 on 2023-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_creator_tvshow_director_tvshow_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='cast',
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='actors',
            field=models.CharField(max_length=255, null=True, verbose_name='cast'),
        ),
    ]
