# Generated by Django 4.1.7 on 2023-05-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tvshow_cast_alter_tvshow_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='tvshow',
            options={'ordering': ['id'], 'verbose_name': 'TVShow', 'verbose_name_plural': 'TVShows'},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
