# Generated by Django 4.1.7 on 2023-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movie_options_alter_tvshow_options_movie_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
