# Generated by Django 4.1.7 on 2023-05-30 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        ('app', '0006_movie_time_tvshow_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, to='django_comments_xtd.xtdcomment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='comments',
            field=models.ManyToManyField(blank=True, to='django_comments_xtd.xtdcomment'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='ratings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
