# Generated by Django 4.1.7 on 2023-05-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='tvshow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActorTvshow', to='app.tvshow'),
        ),
    ]
