# Generated by Django 4.1.7 on 2023-05-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_actor_tvshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='tvshow',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='app.actor'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='tvshows', to='app.actor'),
        ),
    ]
